version: '3.8'

services:
  aps-scraper:
    build: .
    container_name: aps-energy-scraper
    environment:
      - APS_USERNAME=${APS_USERNAME}
      - APS_PASSWORD=${APS_PASSWORD}
    restart: unless-stopped
