version: "3.8"

services:
  aps-scraper:
    build: .
    container_name: aps-energy-scraper
    network_mode: host
    environment:
      - APS_USERNAME=${APS_USERNAME}
      - APS_PASSWORD=${APS_PASSWORD}
    restart: unless-stopped
    depends_on:
      - mosquitto

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data

volumes:
  mosquitto_data: