version: "3.8"

services:
  aps-scraper:
    build: .
    container_name: aps-energy-scraper
    environment:
      - APS_USERNAME=${APS_USERNAME}
      - APS_PASSWORD=${APS_PASSWORD}
    restart: unless-stopped
    depends_on:
      - mosquitto

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - /data/compose/13/mosquitto.conf:/mosquitto/config
      - mosquitto_data:/mosquitto/data

volumes:
  mosquitto_data: